# Generated by Django 5.0.6 on 2024-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('client_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerDetails',
            fields=[
                ('trainer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('trainer_address', models.CharField(max_length=30)),
                ('trainer_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
